### ISSUE TITLE
被ban惹

### ISSUE THREAD

**Issue by xxhomey19** [PPAV-inc/PPAV-crawler#58]
<img width="1002" alt="screen shot 2016-12-13 at 10 22 13 am" src="https://cloud.githubusercontent.com/assets/12113222/21125169/8d2d1c3e-c11e-11e6-9869-1fa77ca13a30.png">

**Comment by peter279k** [comment]
QAQ 其實是有一大部分違反 Facebook 的 term policy (?

**Comment by xxhomey19** [comment]
估計是被人檢舉了吧ＱＱ

**Comment by neighborhood999** [comment]
@xxhomey19 或許可以考慮轉移到 telegram bot 上 XD！

**Comment by LittleWhiteYA** [comment]
telegram 在台灣算是普及的嗎??

**Comment by neighborhood999** [comment]
@LittleWhiteYA 老實說我覺得還不普及，因為使用 Line 的人還是比較多，就算跳到 Telegram 去了也因為使用的人數太少又轉回去使用 Line，我身邊蠻多朋友是這樣！

說不定轉移過去可以變另一個使用 Telegram 的誘因 XD。

**Comment by LittleWhiteYA** [comment]
@neighborhood999 QQ，看了這麼多平台好像只有 Telegram 在這塊是沒有禁止的
但是如果要大部分使用者只是為了搜尋 A 片而特別下載一個 App，我個人覺得用 bot 的意義好像就沒那麼大了QQ

**Comment by peter279k** [comment]
用 App下載，這個服務感覺這意義就不是很大惹。

**Comment by bobbyac01** [comment]
所以不試試看Line嗎QQ?

**Comment by peter279k** [comment]
@bobbyac01 , LINE 也有條款的樣子，就...不行18+的內容 QAQ

**Comment by passerbyid** [comment]
推薦使用 Telegram +1。
身邊用過的人都覺得比 Line、Messenger 好用很多。

**Comment by xxhomey19** [comment]
Telegram 應該也有相關的使用條款吧ＱＱ
問題都不是卡在技術方面，都是卡在會被平台 ban 啊～

**Comment by LittleWhiteYA** [comment]
@peter279k @bobbyac01 @neighborhood999 @passerbyid 
我們要嘗試 telegram bot 了XD
